theme: jekyll-theme-minimal
description: Chris' website
style: |
  <style>
    body {
      background-color: black;
      color: white;
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 0;
      padding: 2rem;
    }

    a {
      color: white;
    }
  </style>

